openapi: "3.0.1"
info:
  title: "rest-cardtracker-cards"
  version: "2021-04-25T16:38:45Z"
servers:
- url: "https://75785a9hn9.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/default"
paths:
  /cards:
    get:
      parameters:
      - name: "start"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cards"
      security:
      - cardtracker-userpools: []
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Card"
        required: true
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - cardtracker-userpools: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /cards/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Card"
      security:
      - cardtracker-userpools: []
    delete:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - cardtracker-userpools: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /collection/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectionCard"
      security:
      - cardtracker-userpools: []
    put:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectionCard"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - cardtracker-userpools: []
    delete:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - cardtracker-userpools: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /collection/{id}/images:
    post:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageRequest"
        required: true
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
      security:
      - cardtracker-userpools: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /collection:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"
      security:
      - cardtracker-userpools: []
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectionCard"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
      - cardtracker-userpools: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
    ImageRequest:
      title: "ImageRequest"
      type: "object"
      properties:
        imageName:
          type: "string"
        side:
          type: "string"
    Collection:
      title: "Collection"
      type: "object"
      properties:
        Items:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "string"
              account:
                type: "string"
              card:
                type: "string"
              count:
                type: "string"
              collected:
                type: "string"
              frontPath:
                type: "string"
              backPath:
                type: "string"
              public:
                type: "boolean"
              variant:
                type: "string"
              parrallel:
                type: "string"
              parrallelnumber:
                type: "string"
              added:
                type: "string"
        LastEvaluatedKey:
          type: "string"
    CollectionCard:
      title: "Collection"
      type: "object"
      properties:
        id:
          type: "string"
        account:
          type: "string"
        card:
          type: "string"
        count:
          type: "string"
        collected:
          type: "string"
        frontPath:
          type: "string"
        backPath:
          type: "string"
        public:
          type: "boolean"
        variant:
          type: "string"
        parrallel:
          type: "string"
        parrallelnumber:
          type: "string"
        added:
          type: "string"
    Image:
      title: "Image"
      type: "object"
      properties:
        signedData:
          type: "object"
        newURL:
          type: "string"
        side:
          type: "string"
    Cards:
      title: "Cards"
      type: "object"
      properties:
        Items:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "string"
              cardnumber:
                type: "string"
              name:
                type: "string"
              team:
                type: "string"
              position:
                type: "string"
              manufacturer:
                type: "string"
              year:
                type: "string"
              set:
                type: "string"
              series:
                type: "string"
              tcdb:
                type: "string"
        LastEvaluatedKey:
          type: "string"
    Card:
      title: "Card"
      type: "object"
      properties:
        id:
          type: "string"
        cardnumber:
          type: "string"
        name:
          type: "string"
        team:
          type: "string"
        position:
          type: "string"
        manufacturer:
          type: "string"
        year:
          type: "string"
        set:
          type: "string"
        series:
          type: "string"
        tcdb:
          type: "string"
  securitySchemes:
    cardtracker-userpools:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
